openapi: 3.0.0
info:
  description: |-
    Urbs 灰度平台灰度策略服务
  version: 1.2.0
  title: urbs-setting
servers:
  - url: https://urbs-setting:8443
    description: 这是内部服务，请替换为实际 URL
tags:
  - name: Version
    description: 获取 urbs-setting 服务版本信息
  - name: User
    description: User 用户相关接口
  - name: Group
    description: Group 群组相关接口
  - name: Product
    description: Product 产品相关接口
  - name: Label
    description: Label 灰度标签相关接口
  - name: Module
    description: Module 产品模块相关接口
  - name: Setting
    description: Setting 产品模块配置项相关接口
components:
  securitySchemes:
    HeaderAuthorizationJWT:
      name: Authorization
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
  schemas:
    NextPageToken:
      title: nextPageToken
      type: string
      description: 用于分页查询时用于获取下一页数据的 token，当为空值时表示没有下一页了
      example: ""
    TotalSize:
      title: totalSize
      type: integer
      format: int64
      description: 当前分页查询的总数据量
      example: 1
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 错误代号
          example: NotFound
        message:
          type: string
          description: 错误详情
          example: user 50c32afae8cf1439d35a87e6 not found
    BoolRes:
      type: object
      properties:
        result:
          type: boolean
          description: 是否成功
          example: true
    Version:
      type: object
      properties:
        name:
          type: string
          description: 服务名称
          example: urbs-setting
        version:
          type: string
          description: 当前版本
          example: v1.2.0
        gitSHA1:
          type: string
          description: git commit hash
          example: cd7e82a
        buildTime:
          type: string
          format: date-time
          description: 打包构建时间
          example: 2020-03-25T06:24:25Z
    Healthz:
      type: object
      properties:
        db_connect:
          type: boolean
          description: 是否连接了数据库
          example: true
    CacheLabelInfo:
      type: object
      properties:
        l:
          type: string
          description: 灰度标签名称
          example: beta
        cls:
          type: array
          description: 灰度标签适用的 Clients 客户端类型列表，当列表为空时表示全适用
          example: ["ios", "android", "web"]
          items:
            type: string
        chs:
          type: array
          description: 灰度标签适用的 Channels 版本通道列表，当列表为空时表示全适用
          example: ["stable", "beta", "dev"]
          items:
            type: string
    LabelsInfoRes:
      type: object
      properties:
        totalSize:
          $ref: "#/components/schemas/TotalSize"
        nextPageToken:
          $ref: "#/components/schemas/NextPageToken"
        result:
          type: array
          items:
            $ref: "#/components/schemas/LabelInfo"
    LabelInfo:
      type: object
      properties:
        hid:
          type: string
          description: 灰度标签的 hid
          example: AwAAAAAAAAB25V_QnbhCuRwF
        product:
          type: string
          description: 灰度标签所属的产品名称
          example: teambition
        name:
          type: string
          description: 灰度标签名称，同一产品下唯一（不能重名）
          example: beta
        desc:
          type: string
          description: 灰度标签描述
        channels:
          type: array
          description: 灰度标签适用版本通道
          example: ["beta"]
          items:
            type: string
        clients:
          type: array
          description: 灰度标签适用客户端类型
          example: ["web"]
          items:
            type: string
        status:
          type: integer
          format: int64
          description: 灰度标签状态（暂未支持）
          example: 0
        created_at:
          type: string
          format: date-time
          description: 灰度标签创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 灰度标签更新时间
          example: 2020-03-25T06:24:25Z
        offline_at:
          type: string
          format: date-time
          description: 灰度标签下线时间
          default: null
          example: null
    MySettingsRes:
      type: object
      properties:
        nextPageToken:
          $ref: "#/components/schemas/NextPageToken"
        result:
          type: array
          items:
            $ref: "#/components/schemas/MySetting"
    MySetting:
      type: object
      properties:
        hid:
          type: string
          description: 配置项的 hid
          example: AwAAAAAAAAB25V_QnbhCuRwF
        module:
          type: string
          description: 配置项所属的功能模块名称
          example: task
        name:
          type: string
          description: 配置项名称，同一产品功能模块下唯一（不能重名）
          example: task-share
        value:
          type: string
          description: 配置项值
          example: disable
        last_value:
          type: string
          description: 配置项值
          example: ""
        created_at:
          type: string
          format: date-time
          description: 灰度标签创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 灰度标签更新时间
          example: 2020-03-25T06:24:25Z
    UsersBody:
      type: object
      properties:
        users:
          type: array
          description: 用户 uid 数组
          items:
            type: string
          example: ["50c32afae8cf1439d35a87e6", "5e69a9bd6ac3cd00213ea969"]
    GroupsRes:
      type: object
      properties:
        totalSize:
          $ref: "#/components/schemas/TotalSize"
        nextPageToken:
          $ref: "#/components/schemas/NextPageToken"
        result:
          type: array
          items:
            $ref: "#/components/schemas/Group"
    Group:
      type: object
      properties:
        uid:
          type: string
          description: 群组的 uid
          example: 5e82d747fe02a50021d339f3
        kind:
          type: string
          description: 群组类型
          example: organization
        desc:
          type: string
          description: 群组的描述
        sync_at:
          type: integer
          format: int64
          description: 群组成员同步时间点，1970 以来的秒数
          example: 1585636012
        created_at:
          type: string
          format: date-time
          description: 灰度标签创建时间
          example: 2020-03-25T06:24:25Z
        updated_at:
          type: string
          format: date-time
          description: 灰度标签更新时间
          example: 2020-03-25T06:24:25Z
    GroupsBody:
      type: object
      properties:
        groups:
          type: array
          description: 用户 uid 数组
          required: true
          items:
            type: object
            properties:
              uid:
                type: string
                description: 群组 uid
                required: true
              kind:
                type: string
                description: 群组类型
                required: true
              desc:
                type: string
                description: 群组描述
                required: false
          example: [{"uid": "50c32afae8cf1439d35a87e6", "kind": "organization"}]
    GroupUpdateBody:
      type: object
      properties:
        type: object
        properties:
          sync_at:
            type: integer
            title: sync_at
            format: int64
            description: 群组成员同步时间点，1970 以来的秒数
          desc:
            type: string
            title: desc
            description: 群组描述
        example: {"sync_at": 1585638012}
paths:
  /version:
    get:
      tags:
        - Version
      summary: 获取版本信息
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
  /healthz:
    get:
      summary: 服务健康检查接口
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthz'
